// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApz5fasLqpYhVvbahaHOST6gAOx1ghicE',
    appId: '1:177944311253:web:07e69da9b69227561a795c',
    messagingSenderId: '177944311253',
    projectId: 'boitexinfo-63060',
    authDomain: 'boitexinfo-63060.firebaseapp.com',
    storageBucket: 'boitexinfo-63060.firebasestorage.app',
    measurementId: 'G-XYGDSSB5TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB81yd8FVTSQTzRTTyhyKTk7W4neNIAd8M',
    appId: '1:177944311253:android:53bd83859690fd771a795c',
    messagingSenderId: '177944311253',
    projectId: 'boitexinfo-63060',
    storageBucket: 'boitexinfo-63060.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJoWM4sljA7eG1YqNZJK8AwKnqbh-PiM8',
    appId: '1:177944311253:ios:03714e43d6620a2c1a795c',
    messagingSenderId: '177944311253',
    projectId: 'boitexinfo-63060',
    storageBucket: 'boitexinfo-63060.firebasestorage.app',
    iosBundleId: 'com.boitexinfo.boitexInfoApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJoWM4sljA7eG1YqNZJK8AwKnqbh-PiM8',
    appId: '1:177944311253:ios:03714e43d6620a2c1a795c',
    messagingSenderId: '177944311253',
    projectId: 'boitexinfo-63060',
    storageBucket: 'boitexinfo-63060.firebasestorage.app',
    iosBundleId: 'com.boitexinfo.boitexInfoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApz5fasLqpYhVvbahaHOST6gAOx1ghicE',
    appId: '1:177944311253:web:010c2cb0d122f29b1a795c',
    messagingSenderId: '177944311253',
    projectId: 'boitexinfo-63060',
    authDomain: 'boitexinfo-63060.firebaseapp.com',
    storageBucket: 'boitexinfo-63060.firebasestorage.app',
    measurementId: 'G-RZPF8YCS8T',
  );

}