// lib/screens/fleet/add_vehicle_page.dart

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:boitex_info_app/models/vehicle.dart';

// 🏎️ THEME CONSTANTS
const Color kCarbonBlack = Color(0xFF1C1C1C);
const Color kRacingRed = Color(0xFFFF2800);
const Color kAsphaltGrey = Color(0xFFF2F3F5);

class AddVehiclePage extends StatefulWidget {
  const AddVehiclePage({super.key});

  @override
  State<AddVehiclePage> createState() => _AddVehiclePageState();
}

class _AddVehiclePageState extends State<AddVehiclePage> {
  final _formKey = GlobalKey<FormState>();

  // Controllers
  final TextEditingController _codeCtrl = TextEditingController(); // e.g. VEH-05
  final TextEditingController _modelCtrl = TextEditingController(); // e.g. Toyota Hilux
  final TextEditingController _plateCtrl = TextEditingController(); // e.g. 00123-116-16
  final TextEditingController _yearCtrl = TextEditingController(text: DateTime.now().year.toString());
  final TextEditingController _mileageCtrl = TextEditingController(text: "0");

  // Selections
  String _selectedFuel = 'Diesel';
  final List<String> _fuelTypes = ['Diesel', 'Essence', 'Hybride', 'Électrique', 'GPL'];

  bool _isSaving = false;

  @override
  void dispose() {
    _codeCtrl.dispose();
    _modelCtrl.dispose();
    _plateCtrl.dispose();
    _yearCtrl.dispose();
    _mileageCtrl.dispose();
    super.dispose();
  }

  Future<void> _saveVehicle() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSaving = true);

    try {
      // 1. Create the Vehicle Object
      // We use a new ID generated by Firestore automatically later,
      // or we can let Firestore generate the doc ID.
      final newVehicle = Vehicle(
        vehicleCode: _codeCtrl.text.toUpperCase().trim(),
        model: _modelCtrl.text.trim(),
        plateNumber: _plateCtrl.text.trim(),
        fuelType: _selectedFuel,
        capacity: 5, // Defaulting to 5 for now
        color: 'Blanc', // Default to White (Standard Fleet Color)
        year: int.parse(_yearCtrl.text),
        currentMileage: int.parse(_mileageCtrl.text),
        status: 'available',
        createdAt: DateTime.now(),
      );

      // 2. Upload to Firestore
      await FirebaseFirestore.instance.collection('vehicles').add(newVehicle.toJson());

      if (mounted) {
        HapticFeedback.heavyImpact();
        Navigator.pop(context); // Close the screen
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("VÉHICULE AJOUTÉ AU GARAGE"),
            backgroundColor: Color(0xFF00C853),
          ),
        );
      }
    } catch (e) {
      setState(() => _isSaving = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Erreur: $e"), backgroundColor: kRacingRed),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: Colors.black),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          "NOUVEAU VÉHICULE",
          style: TextStyle(color: Colors.black, fontWeight: FontWeight.w900, letterSpacing: 1.0, fontSize: 14),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: Form(
          key: _formKey,
          child: ListView(
            padding: const EdgeInsets.all(24),
            physics: const BouncingScrollPhysics(),
            children: [
              const Text(
                "CONFIGURATION",
                style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold, fontSize: 12, letterSpacing: 1.5),
              ),
              const SizedBox(height: 20),

              // 1. IDENTITY SECTION
              _buildTextField(
                controller: _codeCtrl,
                label: "CODE VÉHICULE",
                hint: "Ex: VEH-001",
                icon: CupertinoIcons.barcode,
                textCapitalization: TextCapitalization.characters,
              ),
              const SizedBox(height: 16),
              _buildTextField(
                controller: _modelCtrl,
                label: "MODÈLE",
                hint: "Ex: Fiat Scudo",
                icon: CupertinoIcons.car_detailed,
                textCapitalization: TextCapitalization.words,
              ),
              const SizedBox(height: 16),
              _buildTextField(
                controller: _plateCtrl,
                label: "MATRICULE",
                hint: "Ex: 00123-123-16",
                icon: CupertinoIcons.rectangle_grid_1x2,
              ),

              const SizedBox(height: 32),
              const Text(
                "SPÉCIFICATIONS",
                style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold, fontSize: 12, letterSpacing: 1.5),
              ),
              const SizedBox(height: 20),

              // 2. SPECS ROW
              Row(
                children: [
                  Expanded(
                    child: _buildTextField(
                      controller: _yearCtrl,
                      label: "ANNÉE",
                      hint: "2024",
                      icon: CupertinoIcons.calendar,
                      inputType: TextInputType.number,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: _buildTextField(
                      controller: _mileageCtrl,
                      label: "KILOMÉTRAGE",
                      hint: "0",
                      icon: CupertinoIcons.speedometer,
                      inputType: TextInputType.number,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // 3. FUEL SELECTOR
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                decoration: BoxDecoration(
                  color: kAsphaltGrey,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: DropdownButtonHideUnderline(
                  child: DropdownButton<String>(
                    value: _selectedFuel,
                    isExpanded: true,
                    icon: const Icon(Icons.arrow_drop_down, color: Colors.black),
                    style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.black, fontSize: 16),
                    items: _fuelTypes.map((String value) {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Row(
                          children: [
                            const Icon(CupertinoIcons.drop_fill, size: 16, color: Colors.grey),
                            const SizedBox(width: 12),
                            Text(value),
                          ],
                        ),
                      );
                    }).toList(),
                    onChanged: (newValue) => setState(() => _selectedFuel = newValue!),
                  ),
                ),
              ),

              const SizedBox(height: 40),

              // 4. SUBMIT BUTTON
              SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: kRacingRed, // The Red Button
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                    elevation: 5,
                    shadowColor: kRacingRed.withOpacity(0.4),
                  ),
                  onPressed: _isSaving ? null : _saveVehicle,
                  child: _isSaving
                      ? const CupertinoActivityIndicator(color: Colors.white)
                      : const Text("AJOUTER AU GARAGE", style: TextStyle(fontWeight: FontWeight.w900, letterSpacing: 1.0)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // 🛠️ Helper for consistent text fields
  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    required IconData icon,
    TextInputType inputType = TextInputType.text,
    TextCapitalization textCapitalization = TextCapitalization.none,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.grey)),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          keyboardType: inputType,
          textCapitalization: textCapitalization,
          style: const TextStyle(fontWeight: FontWeight.bold, color: kCarbonBlack),
          validator: (val) => val == null || val.isEmpty ? "Requis" : null,
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: TextStyle(color: Colors.grey.shade400, fontWeight: FontWeight.normal),
            prefixIcon: Icon(icon, size: 20, color: Colors.grey),
            filled: true,
            fillColor: kAsphaltGrey,
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
            focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: kRacingRed, width: 2)),
            contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          ),
        ),
      ],
    );
  }
}